export const fields = [
  "Tên sản phẩm",
  "Mã SKU",
  "Mã BARCODE",
  "Theo dõi kho (Có/Không)",
  "Danh mục",
  "Thuộc tính",
  "Hoa hồng CTV (%)",
  "Xu cho đại lý",
  "Mô tả",
  "Nội dung cho CTV",
  "Trạng thái (Ẩn/Hiện)",
  "Tiêu đề SEO",
  "Miêu tả SEO",
  "Có phân loại (Có/Không)",
  "Phân loại chính",
  "Phân loại phụ",
  "DS phân loại",
  "Giá bán lẻ",
  "Giá nhập",
  "Hình ảnh",
];
