export const IMG_NOT_FOUND = "/images/no_img.png"
export const IMG_NOT_FOUND_2 = "/images/no_img.png"
export const IMG_LOADING_PAGE = ""
export const IMG_NOT_AVATAR = "/images/people.png"
export const API_KEY_FONT = "AIzaSyDIAniO77CXyauCOf7YwBTRKICq9JMbP8E"
