/// REGISTER REDUCER
export const LOADING_CREATE_QUESTION = "LOADING_CREATE_QUESTION";
export const NONE = "NONE";
export const LOADING = "LOADING";
/// LOGTIN REDUCER
export const AUTHENTICATION_LOGIN = "AUTHENTICATION_LOGIN";
export const RESET_STATUS_LOADING = "RESET_STATUS_LOADING";
/// FORGOT REDUCER
export const SUCCESS = "SUCCESS";
/// REGISTER REDUCER
export const USER_REGISTER = "USER_REGISTER";
export const FAILURE = "FAILURE";
/// LOGTIN REDUCER
export const UPDATE_STATUS_SYNC_SHIPMENT = "UPDATE_STATUS_SYNC_SHIPMENT";
export const USER_PHONE_FORGOT = "USER_PHONE_FORGOT";

//BRANCH
export const CHANGE_BRANCH = "CHANGE_BRANCH";

export const FETCH_PERMISSION = "FETCH_PERMISSION";
export const LOAD_PERMISSION = "LOAD_PERMISSION";

/// STORE REDUCER
export const FETCH_ALL_STORE = "FETCH_ALL_STORE";
export const FETCH_ID_STORE = "FETCH_ID_STORE";
export const FETCH_ALL_TYPESTORE = "FETCH_ALL_TYPESTORE";

export const FETCH_ALL_DECENTRALIZATION = "FETCH_ALL_DECENTRALIZATION";
export const FETCH_ID_DECENTRALIZATION = "FETCH_ID_DECENTRALIZATION";

export const FETCH_ALL_STAFF = "FETCH_ALL_STAFF";
export const FETCH_ID_STAFF = "FETCH_ID_STAFF";
export const UPDATE_STAFF_TO_SALE = "UPDATE_STAFF_TO_SALE";

/// STORE_ADDRESS REDUCERS
export const FETCH_ALL_STORE_ADDRESS = "FETCH_ALL_STORE_ADDRESS";
export const FETCH_ID_STORE_ADDRESS = "FETCH_ID_STORE_ADDRESS";
export const FETCH_SHIP_CONFIG = "FETCH_SHIP_CONFIG";
/// CATEGORY PRODUCT_ADDRESS REDUCERS
export const FETCH_ALL_CATEGORY_PRODUCT = "FETCH_ALL_CATEGORY_PRODUCT";
export const FETCH_ID_CATEGORY_PRODUCT = "FETCH_ALL_CATEGORY_PRODUCT";
/// PRODUCT UNITS
export const FETCH_ALL_PRODUCT_UNITS = "FETCH_ALL_PRODUCT_UNITS";
/// ATTRIBUTE SEARCH REDUCERS
export const FETCH_ALL_ATTRIBUTE_SEARCH = "FETCH_ALL_ATTRIBUTE_SEARCH";
export const FETCH_ALL_ATTRIBUTE_SEARCH_PRODUCT =
  "FETCH_ALL_ATTRIBUTE_SEARCH_PRODUCT";

/// PRODUCT REDUCER
export const FETCH_ALL_PRODUCT = "FETCH_ALL_PRODUCT";
export const FETCH_ID_PRODUCT = "FETCH_ID_PRODUCT";
export const FETCH_ALL_PRODUCT_LIST = "FETCH_ALL_PRODUCT_LIST";
export const FETCH_ALL_PRODUCT_TIKI = "FETCH_ALL_PRODUCT_TIKI";
export const FETCH_ALL_PRODUCT_SENDO = "FETCH_ALL_PRODUCT_SENDO";
export const FETCH_ALL_PRODUCT_SHOPEE = "FETCH_ALL_PRODUCT_SHOPEE";
export const FETCH_ID_PRODUCT_AGENCY_PRICE = "FETCH_ID_PRODUCT_AGENCY_PRICE";

export const UPLOAD_PRODUCT_IMG = "UPLOAD_PRODUCT_IMG";
export const UPLOAD_PRODUCT_VIDEO = "UPLOAD_PRODUCT_VIDEO";
export const UPLOAD_LIST_PRODUCT_VIDEO = "UPLOAD_LIST_PRODUCT_VIDEO";
export const UPLOAD_ALL_PRODUCT_IMG = "UPLOAD_ALL_PRODUCT_IMG";
export const UPLOAD_ALL_PRODUCT_IMG_V2 = "UPLOAD_ALL_PRODUCT_IMG_V2";
export const UPLOAD_ALL_DISTRIBUTE_IMG = "UPLOAD_ALL_DISTRIBUTE_IMG";
export const IMPORT_FILE_PRODUCTS = "IMPORT_FILE_PRODUCTS";
export const SET_LEVEL_PRODUCT = "SET_LEVEL_PRODUCT";

/// PACKAGE PRODUCT REDUCERS

export const FETCH_ALL_PACKAGE_PRODUCT = "FETCH_ALL_PACKAGE_PRODUCT";

/// ATTRIBUTE REDUCER
export const FETCH_ALL_ATTRIBUTE_PRODUCT = "FETCH_ALL_ATTRIBUTE_PRODUCT";

///DISCOUNT REDUCER
export const FETCH_ALL_DISCOUNT = "FETCH_ALL_DISCOUNT";

export const FETCH_ID_DISCOUNT = "FETCH_ID_DISCOUNT";
export const UPLOAD_DISCOUNT_IMG = "UPLOAD_DISCOUNT_IMG";

///vOUCHER REDUCER
export const FETCH_ALL_VOUCHER = "FETCH_ALL_VOUCHER";

export const FETCH_ID_VOUCHER = "FETCH_ID_VOUCHER";
export const UPLOAD_VOUCHER_IMG = "UPLOAD_VOUCHER_IMG";

///COMBO REDUCER
export const FETCH_ALL_COMBO = "FETCH_ALL_COMBO";

export const FETCH_ID_COMBO = "FETCH_ID_COMBO";

export const FETCH_ALL_BONUS_PRODUCT = "FETCH_ALL_BONUS_PRODUCT";
export const UPLOAD_BONUS_PRODUCT_IMG = "UPLOAD_BONUS_PRODUCT_IMG";
export const FETCH_ID_BONUS_PRODUCT = "FETCH_ID_BONUS_PRODUCT";
export const UPLOAD_COMBO_IMG = "UPLOAD_COMBO_IMG";

//SHIFT REDUCER
export const FETCH_ALL_SHIFT = "FETCH_ALL_SHIFT";

export const FETCH_ID_SHIFT = "FETCH_ID_SHIFT";
export const FETCH_ID_CALENDAR_SHIFT = "FETCH_ID_CALENDAR_SHIFT";
export const FETCH_ALL_CALENDAR_SHIFT = "FETCH_ALL_CALENDAR_SHIFT";
export const FETCH_ALL_TIME_SHEET = "FETCH_ALL_TIME_SHEET";
export const FETCH_ALL_REQUEST_MOBILE = "FETCH_ALL_REQUEST_MOBILE";
export const FETCH_ALL_REQUEST_REMOTE = "FETCH_ALL_REQUEST_REMOTE";
export const FETCH_STAFF_MOBILE_CHECKIN = "FETCH_STAFF_MOBILE_CHECKIN";
///CATEGORY BLOG REDUCER
export const FETCH_ALL_CATEGORY_BLOG = "FETCH_ALL_CATEGORY_BLOG";
export const FETCH_ID_CATEGORY_BLOG = "FETCH_ID_CATEGORY_BLOG";
export const UPLOAD_CATEGORY_BLOG_IMG = "UPLOAD_CATEGORY_BLOG_IMG";

//CONFIG VIP
export const UPLOAD_CONFIG_VIP_IMG_LOGIN = "UPLOAD_CONFIG_VIP_IMG_LOGIN";
export const UPLOAD_CONFIG_VIP_IMG_LOGO = "UPLOAD_CONFIG_VIP_IMG_LOGO";
export const UPLOAD_CONFIG_VIP_IMG_LOGO_AFTER =
  "UPLOAD_CONFIG_VIP_IMG_LOGO_AFTER";

export const FETCH_ALL_BANNER_ADS = "FETCH_ALL_BANNER_ADS";
export const FETCH_ID_BANNER_ADS = "FETCH_ID_BANNER_ADS";
export const UPLOAD_BANNER_ADS_IMG = "UPLOAD_BANNER_ADS_IMG";

///BLOG REDUCER
export const FETCH_ALL_BLOG = "FETCH_ALL_BLOG";
export const FETCH_ID_BLOG = "FETCH_ID_BLOG";
export const UPLOAD_BLOG_IMG = "UPLOAD_BLOG_IMG";
export const FETCH_ALL_TRAIN_COURSE = "FETCH_ALL_TRAIN_COURSE";
export const FETCH_ID_TRAIN_COURSE = "FETCH_ID_TRAIN_COURSE";
export const FETCH_ID_TRAIN_QUIZ = "FETCH_ID_TRAIN_QUIZ";
export const FETCH_ALL_TRAIN_LESSON = "FETCH_ALL_TRAIN_LESSON";
export const FETCH_ID_TRAIN_LESSON = "FETCH_ID_TRAIN_LESSON";
export const FETCH_ALL_TRAIN_QUIZ = "FETCH_ALL_TRAIN_QUIZ";

/// SHIPMENT REDUCERS
export const FETCH_ALL_SHIPMENT = "FETCH_ALL_SHIPMENT";
export const FETCH_ID_SHIPMENT = "FETCH_ID_SHIPMENT";
export const RESET_ALL_SHIPMENT = "RESET_ALL_SHIPMENT";
export const FETCH_ALL_CALCULATE_SHIPMENT = "FETCH_ALL_CALCULATE_SHIPMENT";
/// PAYMENT REDUCERS
export const FETCH_ALL_PAYMENT = "FETCH_ALL_PAYMENT";
export const FETCH_ID_PAYMENT = "FETCH_ID_PAYMENT";

/// CUSTOMER REDUCERS

export const FETCH_ALL_CUSTOMER = "FETCH_ALL_CUSTOMER";
export const FETCH_ALL_CUSTOMER_BY_INFERRAL_PHONE =
  "FETCH_ALL_CUSTOMER_BY_INFERRAL_PHONE";
export const FETCH_ID_CUSTOMER = "FETCH_ID_CUSTOMER";
export const CREATED_CUSTOMER = "CREATED_CUSTOMER";
export const FETCH_ALL_POINT_HISTORY = "FETCH_ALL_POINT_HISTORY";
export const CHANGE_ROLE_CUSTOMER = "CHANGE_ROLE_CUSTOMER";
export const UPDATE_ROLE_CUSTOMER_FOR_INTERFACE =
  "UPDATE_ROLE_CUSTOMER_FOR_INTERFACE";
export const ADD_SUB_POINT_CUSTOMER = "ADD_SUB_POINT_CUSTOMER";
export const ADD_SUB_POINT_BONUS_CUSTOMER = "ADD_SUB_POINT_BONUS_CUSTOMER";
export const FETCH_HISTORIES_LEVEL_CUSTOMER = "FETCH_HISTORIES_LEVEL_CUSTOMER";
export const CHANGE_STATUS_CUSTOMER = "CHANGE_STATUS_CUSTOMER";
export const CHANGE_PASSWORD_CUSTOMER = "CHANGE_PASSWORD_CUSTOMER";
export const CUSTOMER_STATUS_WATING_REVIEW = 0;
export const CUSTOMER_STATUS_CANCEL = 1;
export const CUSTOMER_STATUS_APPROVE = 2;
export const CUSTOMER_STATUS_BLOCK = 3;
export const CUSTOMER_ROLE_ALL = 0;
export const CUSTOMER_ROLE_NORMAL = -1;
export const CUSTOMER_ROLE_CTV = 1;
export const CUSTOMER_ROLE_AGENCY = 2;

/// GROUP CUSTOMER REDUCERS

export const FETCH_ALL_GROUP_CUSTOMER = "FETCH_ALL_GROUP_CUSTOMER";
export const FETCH_GROUP_CUSTOMER = "FETCH_GROUP_CUSTOMER";
export const CREATE_GROUP_CUSTOMER = "CREATE_GROUP_CUSTOMER";
export const UPDATE_GROUP_CUSTOMER = "UPDATE_GROUP_CUSTOMER";
export const DELETE_GROUP_CUSTOMER = "DELETE_GROUP_CUSTOMER";

/// CUSTOMER SALES REDUCERS
export const FETCH_ALL_CUSTOMER_SALE = "FETCH_ALL_CUSTOMER_SALE";
export const FETCH_ID_CUSTOMER_SALE = "FETCH_ID_CUSTOMER_SALE";
export const CREATED_CUSTOMER_SALE = "CREATED_CUSTOMER_SALE";
export const CREATE_ACCOUNT_FOR_CUSTOMER_SALE =
  "CREATE_ACCOUNT_FOR_CUSTOMER_SALE";

/// REVENUE_EXPENDITURES REDUCERS

export const FETCH_ALL_REVENUE_EXPENDITURES = "FETCH_ALL_REVENUE_EXPENDITURES";
export const FETCH_REVENUE_EXPENDITURES_BY_ID =
  "FETCH_REVENUE_EXPENDITURES_BY_ID";
//USER REDUCERS
export const FETCH_ID_USER = "FETCH_ID_USER";
export const UPLOAD_USER_IMG = "UPLOAD_USER_IMG";
export const UPLOAD_STORE_IMG = "UPLOAD_STORE_IMG";

// CONFIG VIP
export const FETCH_CONFIG_VIP_USER = "FETCH_CONFIG_VIP_USER";

/// BILL REDUCERS
export const FETCH_ALL_BILL = "FETCH_ALL_BILL";
export const FETCH_ID_BILL = "FETCH_ID_BILL";
export const FETCH_BILL_HISTORY = "FETCH_BILL_HISTORY";
export const DELETE_ORDER = "DELETE_ORDER";

/// HISTORY PAY
export const FETCH_ALL_HISTORY_PAY = "FETCH_ALL_HISTORY_PAY";
export const FETCH_ID_HISTORY_PAY = "FETCH_ID_BILL";
export const GET_CALCULATE = "GET_CALCULATE";
//DELIVERY
export const FETCH_DELIVERY_HISTORY = "FETCH_DELIVERY_HISTORY";

export const FETCH_ID_CHAT = "FETCH_ID_CHAT";
export const FETCH_ID_CHAT_USER = "FETCH_ID_CHAT_USER";
export const FETCH_ALL_CHAT = "FETCH_ALL_CHAT";
export const ALERT_UID_STATUS = "ALERT_UID_STATUS";

export const SHOW_LOADING = "SHOW_LOADING";
export const SHOW_LOADING_SPINNERS = "SHOW_LOADING_SPINNERS";
export const FETCH_ALL_BADGE = "FETCH_ALL_BADGE";

/// AGENCY

export const FETCH_ALL_AGENCY_CONFIG = "FETCH_ALL_AGENCY_CONFIG";
export const FETCH_ALL_AGENCY_STEP = "FETCH_ALL_AGENCY_STEP";
export const FETCH_ALL_AGENCY_STEP_IMPORT = "FETCH_ALL_AGENCY_STEP_IMPORT";
export const FETCH_ALL_AGENCY_HISTORY_PAYMENT =
  "FETCH_ALL_AGENCY_HISTORY_PAYMENT";
export const FETCH_ALL_AGENCY_TYPE = "FETCH_ALL_AGENCY_TYPE";
export const FETCH_ALL_AGENCY_TOP_REPORT = "FETCH_ALL_AGENCY_TOP_REPORT";
export const FETCH_REPORT_IMPORT_SELL = "FETCH_REPORT_IMPORT_SELL";

export const FETCH_ALL_AGENCY = "FETCH_ALL_AGENCY";
export const FETCH_ALL_AGENCY_REQUEST_PAYMENT =
  "FETCH_ALL_AGENCY_REQUEST_PAYMENT";

export const GET_BONUS_AGENCY_CONFIG = "GET_BONUS_AGENCY_CONFIG";
export const UPDATE_BONUS_AGENCY_CONFIG = "UPDATE_BONUS_AGENCY_CONFIG";
export const ADD_BONUS_STEP_AGENCY = "ADD_BONUS_STEP_AGENCY";
export const UPDATE_BONUS_STEP_AGENCY = "UPDATE_BONUS_STEP_AGENCY";
export const DELETE_BONUS_STEP_AGENCY = "DELETE_BONUS_STEP_AGENCY";
export const CHANGE_PRICE_BALANCE_AGENCY = "CHANGE_PRICE_BALANCE_AGENCY";
export const FETCH_HISTORIES_BALANCE_AGENCY = "FETCH_HISTORIES_BALANCE_AGENCY";
export const FETCH_ALL_AGENCY_TOP_COMMISSION =
  "FETCH_ALL_AGENCY_TOP_COMMISSION";
export const UPDATE_PERCENT_DISCOUNT_AGENCY = "UPDATE_PERCENT_DISCOUNT_AGENCY";
export const UPDATE_COMMISSION_AGENCY = "UPDATE_COMMISSION_AGENCY";
export const HISTORY_CHANGE_LEVEL_AGENCY = "HISTORY_CHANGE_LEVEL_AGENCY";
/////

export const FETCH_ALL_REVIEW = "FETCH_ALL_REVIEW";

export const SHOW_LOADING_LAZY = "SHOW_LOADING_LAZY";
export const SHOW_LOADING_SHIPPER = "SHOW_LOADING_SHIPPER";
export const FETCH_ALL_COLLABORATOR_CONFIG = "FETCH_ALL_COLLABORATOR_CONFIG";
export const FETCH_ALL_COLLABORATOR_STEP = "FETCH_ALL_COLLABORATOR_STEP";

export const FETCH_ALL_COLLABORATOR = "FETCH_ALL_COLLABORATOR";
export const FETCH_ALL_COLLABORATOR_REQUEST_PAYMENT =
  "FETCH_ALL_COLLABORATOR_REQUEST_PAYMENT";
export const FETCH_ALL_COLLABORATOR_TOP_REPORT =
  "FETCH_ALL_COLLABORATOR_TOP_REPORT";
export const FETCH_REWARD_POINT = "FETCH_REWARD_POINT";
export const FETCH_HISTORIES_BALANCE_COLLABORATOR =
  "FETCH_HISTORIES_BALANCE_COLLABORATOR";
export const CHANGE_PRICE_BALANCE = "CHANGE_PRICE_BALANCE";

////ACCUMULATE POINT
export const FETCH_ALL_ACCUMULATE_POINT = "FETCH_ALL_ACCUMULATE_POINT";
export const FETCH_ALL_REQUEST_BONUS_ACCUMULATE_POINT =
  "FETCH_ALL_REQUEST_BONUS_ACCUMULATE_POINT";
export const CONFIRM_REQUEST_BONUS_ACCUMULATE_POINT =
  "CONFIRM_REQUEST_BONUS_ACCUMULATE_POINT";
export const REQUEST_BONUS_POINT_STATUS_PROCESSING = 0;
export const REQUEST_BONUS_POINT_STATUS_CANCEL = 1;
export const REQUEST_BONUS_POINT_STATUS_APPROVED = 2;

///CATEGORY BLOG REDUCER
export const FETCH_ALL_SCHEDULE = "FETCH_ALL_SCHEDULE";
export const FETCH_ID_SCHEDULE = "FETCH_ID_SCHEDULE";

export const FETCH_ALL_POPUP = "FETCH_ALL_POPUP";
export const FETCH_ID_POPUP = "FETCH_ID_POPUP";
export const UPLOAD_POPUP_IMG = "UPLOAD_POPUP_IMG";

export const FETCH_TOPTEN_REPORT = "FETCH_TOPTEN_REPORT";
export const FETCH_OVERVIEW_REPORT = "FETCH_OVERVIEW_REPORT";

export const FETCH_PLACE_DISTRICT = "FETCH_PLACE_DISTRICT";
export const FETCH_PLACE_PROVICE = "FETCH_PLACE_PROVICE";
export const FETCH_PLACE_WARDS = "FETCH_PLACE_WARDS";

export const FETCH_THEME = "FETCH_THEME";

export const UPLOAD_THEME_IMG_FACE = "UPLOAD_THEME_IMG_FACE";
export const UPLOAD_THEME_IMG_FAVICON = "UPLOAD_THEME_IMG_FAVICON";
export const UPLOAD_THEME_IMG_LOGO = "UPLOAD_THEME_IMG_LOGO";
export const FETCH_ALL_NOTIFICATION = "FETCH_ALL_NOTIFICATION";

export const ERROR_RESPONSE = "ERROR_RESPONSE";

export const FETCH_ALL_COLLABORATOR_HISTORY_PAYMENT =
  "FETCH_ALL_COLLABORATOR_HISTORY_PAYMENT";

export const POST_ID_HELP = "POST_ID_HELP";
export const POST_ID_CONTACT = "POST_ID_CONTACT";
export const POST_ID_ABOUT = "POST_ID_ABOUT";
export const POST_ID_TERM = "POST_ID_TERM";
export const POST_ID_RETURN_POLICY = "POST_ID_RETURN_POLICY";
export const POST_ID_SUPPORT_POLICY = "POST_ID_SUPPORT_POLICY";
export const POST_ID_PRIVACY_POLICY = "POST_ID_PRIVACY_POLICY";

// ADD ORDER PROUCT

export const FETCH_ALL_ORDER_PRODUCT = "FETCH_ALL_ORDER_PRODUCT";
export const FETCH_ID_ORDER_PRODUCT = "FETCH_ID_ORDER_PRODUCT";
export const FETCH_ALL_VOUCHER_PRODUCT = "FETCH_ALL_VOUCHER_PRODUCT";
export const FETCH_ALL_PERTION_INFO = "FETCH_ALL_PERTION_INFO";
export const FETCH_SEARCH_PERSION = "FETCH_SEARCH_PERSION";
export const FETCH_INFO_PERSION = "FETCH_INFO_PERSION";
export const FETCH_ALL_COMBO_PRODUCT = "FETCH_ALL_COMBO_PRODUCT";
export const ALERT_UIDS_STATUS = "ALERT_UIDS_STATUS";

// ADD BRANCH STORE

export const FETCH_BRANCH_STORE = "FETCH_BRANCH_STORE";
export const DELETE_BRANCH_STORE = "DELETE_BRANCH_STORE";
export const FETCH_BRANCH_STORE_LOADING = "FETCH_BRANCH_STORE_LOADING";
export const FETCH_BRANCH_STORE_NONE = "FETCH_BRANCH_STORE_NONE";

// ADD SUPPLIER

export const FETCH_ALL_SUPPLIER = "FETCH_ALL_SUPPLIER";
export const FETCH_ID_SUPPLIER = "FETCH_ID_SUPPLIER";

// ADD Inventory

export const FETCH_ALL_SHEETS_INVENTORY = "FETCH_ALL_SHEETS_INVENTORY";
export const FETCH_ALL_ITEM_INVENTORY = "FETCH_ALL_ITEM_INVENTORY";
export const FETCH_ALL_HISTORY_INVENTORY = "FETCH_ALL_HISTORY_INVENTORY";

// ADD IMPORT STOCK

export const FETCH_ALL_IMPORT_STOCK = "FETCH_ALL_IMPORT_STOCK";
export const FETCH_DETAIL_IMPORT_STOCK = "FETCH_DETAIL_IMPORT_STOCK";

export const FETCH_ALL_TRANSFER_STOCK = "FETCH_ALL_TRANSFER_STOCK";
export const FETCH_DETAIL_TRANSFER_STOCK = "FETCH_DETAIL_TRANSFER_STOCK";
export const FETCH_ALL_TRANSFER_STOCK_RECEIVER =
  "FETCH_ALL_TRANSFER_STOCK_RECEIVER";
// ADD REPORT

export const FETCH_ALL_REPORT_INVENTORY = "FETCH_ALL_REPORT_INVENTORY";
export const FETCH_IMPORT_EXPORT_STOCK = "FETCH_IMPORT_EXPORT_STOCK";
export const FETCH_ALL_INVENTORY_HISTORY = "FETCH_ALL_INVENTORY_HISTORY";
export const FETCH_REPORT_PROFIT = "FETCH_REPORT_PROFIT";
export const FETCH_REPORT_PROFIT_COMPARE = "FETCH_REPORT_PROFIT_COMPARE";
export const FETCH_ALL_REPORT_CUSTOMER_DEBT = "FETCH_ALL_REPORT_CUSTOMER_DEBT";
export const FETCH_ALL_REPORT_SUPPLIER_DEBT = "FETCH_ALL_REPORT_SUPPLIER_DEBT";

export const FETCH_REPORT_EXPENDITURE = "FETCH_REPORT_EXPENDITURE";
export const FETCH_REPORT_REVENUE = "FETCH_REPORT_REVENUE";
export const FETCH_REPORT_REVENUE_PROFIT = "FETCH_REPORT_REVENUE_PROFIT";

// ADD POST ORDER
export const FETCH_LIST_POS_ORDER = "FETCH_LIST_POS_ORDER";
export const FETCH_LIST_POS_ORDER_LOADING = "FETCH_LIST_POS_ORDER_LOADING";

export const POS_ORDER_PAYMENT_LOADING = "POS_ORDER_PAYMENT_LOADING";
export const POS_ORDER_PAYMENT_SUCCESS = "POS_ORDER_PAYMENT_SUCCESS";
export const POS_ORDER_PAYMENT_FAILD = "POS_ORDER_PAYMENT_FAILD";
export const CHANGE_STATUS_ALLOW_PRINT = "CHANGE_STATUS_ALLOW_PRINT";
export const FROM_EDIT_ORDER = "FROM_EDIT_ORDER";
export const LOADING_CHANGE_QUANTITY_LINE_ITEM =
  "LOADING_CHANGE_QUANTITY_LINE_ITEM";
export const NONE_CHANGE_QUANTITY_LINE_ITEM = "NONE_CHANGE_QUANTITY_LINE_ITEM";

export const CREATE_POS_ORDER_ITEM = "CREATE_POS_ORDER_ITEM";
export const FETCH_LIST_CART_ITEM = "FETCH_LIST_CART_ITEM";

export const USE_VOUCHER_CART_LOAD = "USE_VOUCHER_CART_LOAD";
export const USE_VOUCHER_CART_DONE = "USE_VOUCHER_CART_DONE";

export const FETCH_ALL_GENERAL_SETTING = "FETCH_ALL_GENERAL_SETTING";

export const FETCH_INFO_CUSTOMER = "FETCH_INFO_CUSTOMER";
export const UPDATE_PRICE_ITEM = "UPDATE_PRICE_ITEM";

// GROUP CUSTOMER
export const TYPE_COMPARE_TOTAL_FINAL_COMPLETED = 0; // Tổng mua (Chỉ đơn hoàn thành trừ trả hàng),
export const TYPE_COMPARE_TOTAL_FINAL_WITH_REFUND = 1; // Tổng mua (Tất cả trạng thái đơn trừ trả hàng),
export const TYPE_COMPARE_POINT = 2; // Xu hiện tại,
export const TYPE_COMPARE_COUNT_ORDER = 3; // Số lần mua hàng
export const TYPE_COMPARE_MONTH_BIRTH = 4; // tháng sinh nhật
export const TYPE_COMPARE_AGE = 5; // tuổi
export const TYPE_COMPARE_SEX = 6; // giới tính,
export const TYPE_COMPARE_PROVINCE = 7; // tỉnh,
export const TYPE_COMPARE_DATE_REG = 8; // ngày đăng ký
export const TYPE_COMPARE_CTV = 9; // cộng tác viên
export const TYPE_COMPARE_AGENCY = 10; // Đại lý
export const TYPE_COMPARE_GROUP_CUSTOMER = 11; // Theo nhóm khách hàng

// HISTORY OPERATION
export const GET_HISTORY_OPERATION = "GET_HISTORY_OPERATION";
export const OPERATION_ACTION_ADD = "OPERATION_ACTION_ADD";
export const OPERATION_ACTION_DELETE = "OPERATION_ACTION_DELETE";
export const OPERATION_ACTION_UPDATE = "OPERATION_ACTION_UPDATE";
export const OPERATION_ACTION_CANCEL = "OPERATION_ACTION_CANCEL";
export const FUNCTION_TYPE_PRODUCT = "FUNCTION_TYPE_PRODUCT";
export const FUNCTION_TYPE_INVENTORY = "FUNCTION_TYPE_INVENTORY";
export const FUNCTION_TYPE_CATEGORY_PRODUCT = "FUNCTION_TYPE_CATEGORY_PRODUCT";
export const FUNCTION_TYPE_CATEGORY_POST = "FUNCTION_TYPE_CATEGORY_POST";
export const FUNCTION_TYPE_ORDER = "FUNCTION_TYPE_ORDER";
export const FUNCTION_TYPE_THEME = "FUNCTION_TYPE_THEME";
export const FUNCTION_TYPE_PROMOTION = "FUNCTION_TYPE_PROMOTION";

// Manage Inventory
export const TYPE_EDIT_STOCK = 0; //Cân bằng sửa kho
export const TYPE_TALLY_SHEET_STOCK = 1; //Cân bằng kiểm kho
export const TYPE_IMPORT_STOCK = 2; //Nhập kho
export const TYPE_INIT_STOCK = 3; //Khởi tạo kho
export const TYPE_EXPORT_ORDER_STOCK = 4; //Xuất đơn hàng
export const TYPE_REFUND_IMPORT_STOCK = 5; //Hoàn trả nhập hàng
export const TYPE_REFUND_ORDER = 6; //Hoàn trả đơn hàng
export const TYPE_EDIT_COST_OF_CAPITAL = 7; //Điều chỉnh giá vốn
export const TYPE_IMPORT_AUTO_CHANGE_COST_OF_CAPITAL = 8; //Tự động điều chỉnh giá vốn khi nhập hàng
export const TYPE_TRANSFER_STOCK_RECEIVER = 9; //Nhận hàng từ chi nhánh khách
export const TYPE_TRANSFER_STOCK_SENDER = 10; //Chuyển hàng đến chi nhánh khác

//Mini Game
export const LIST_GAME_SPIN_WHEELS = "LIST_GAME_SPIN_WHEELS";
export const GAME_SPIN_WHEELS = "GAME_SPIN_WHEELS";
export const ADD_GAME_SPIN_WHEELS = "ADD_GAME_SPIN_WHEELS";
export const UPDATE_GAME_SPIN_WHEELS = "UPDATE_GAME_SPIN_WHEELS";
export const DELETE_GAME_SPIN_WHEELS = "DELETE_GAME_SPIN_WHEELS";
export const LIST_GIFT_GAME_SPIN_WHEELS = "LIST_GIFT_GAME_SPIN_WHEELS";
export const GIFT_GAME_SPIN_WHEELS = "GIFT_GAME_SPIN_WHEELS";
export const ADD_GIFT_GAME_SPIN_WHEELS = "ADD_GIFT_GAME_SPIN_WHEELS";
export const SAVE_GIFT_GAME_SPIN_WHEELS = "SAVE_GIFT_GAME_SPIN_WHEELS";
export const SAVE_GIFT_GAME_SPIN_WHEELS_MESSAGE =
  "SAVE_GIFT_GAME_SPIN_WHEELS_MESSAGE";
export const UPDATE_GIFT_GAME_SPIN_WHEELS = "UPDATE_GIFT_GAME_SPIN_WHEELS";
export const DELETE_GIFT_GAME_SPIN_WHEELS = "DELETE_GIFT_GAME_SPIN_WHEELS";

// Type Gift spin wheel
export const GIFT_IS_COIN = 0;
export const GIFT_IS_ITEM = 1;
export const GIFT_IS_TEXT = 2;
export const GIFT_IS_LUCKY_AFTER = 3;
export const GIFT_IS_LOST_TURN = 4;

//Type Background Game spin wheel
export const TYPE_IMAGE_DEFAULT = 0;
export const TYPE_IMAGE_SELF_POSTED = 1;

//Game đoán số
export const LIST_GAME_GUESS_NUMBERS = "LIST_GAME_GUESS_NUMBERS";
export const GAME_GUESS_NUMBERS = "GAME_GUESS_NUMBERS";
export const ADD_GAME_GUESS_NUMBERS = "ADD_GAME_GUESS_NUMBERS";
export const UPDATE_GAME_GUESS_NUMBERS = "UPDATE_GAME_GUESS_NUMBERS";
export const DELETE_GAME_GUESS_NUMBERS = "DELETE_GAME_GUESS_NUMBERS";

//Spin Wheel For + Guess Numbers For
export const GROUP_CUSTOMER_ALL = 0;
export const GROUP_CUSTOMER_CTV = 1;
export const GROUP_CUSTOMER_AGENCY = 2;
export const GROUP_CUSTOMER_BY_CONDITION = 4;

// Status spin wheel + guess numbers
export const PROGRESSING = 0;
export const CANCELED = 1;
export const COMPLETED = 2;

//User Manage Sale
export const FETCH_ALL_SALE_CONFIG = "FETCH_ALL_SALE_CONFIG";
export const FETCH_ALL_SALE_STEP = "FETCH_ALL_SALE_STEP";
export const ADD_SALE_STEP = "ADD_SALE_STEP";
export const UPDATE_SALE_STEP = "UPDATE_SALE_STEP";
export const REMOVE_SALE_STEP = "REMOVE_SALE_STEP";
export const ADD_CUSTOMER_TO_SALE = "ADD_CUSTOMER_TO_SALE";
export const STATISTICAL_SALE_USER = "STATISTICAL_SALE_USER";

//Sale Manage
export const STATISTICAL_SALE = "STATISTICAL_SALE";
export const FETCH_ALL_CUSTOMER_OF_SALE = "FETCH_ALL_CUSTOMER_OF_SALE";
export const FETCH_DETAIL_OF_CUSTOMER = "FETCH_DETAIL_OF_CUSTOMER";
export const ADD_CUSTOMER_OF_SALE = "ADD_CUSTOMER_OF_SALE";
export const UPDATE_CUSTOMER_OF_SALE = "UPDATE_CUSTOMER_OF_SALE";
export const REMOVE_CUSTOMER_OF_SALE = "REMOVE_CUSTOMER_OF_SALE";
export const FETCH_ALL_SALE_TOP_COMMISSION = "FETCH_ALL_SALE_TOP_COMMISSION";
export const FETCH_LIST_IDS_CUSTOMER_FROM_SALE =
  "FETCH_LIST_IDS_CUSTOMER_FROM_SALE";

//TYPE_CUSTOMER
export const TYPE_CUSTOMER_RETAIL = 0;
export const TYPE_CUSTOMER_COLLABORATOR = 1;
export const TYPE_CUSTOMER_AGENCY = 2;

//ATTRIBUTE_SEARCH
export const FETCH_LIST_ATTRIBUTE_PRODUCT_SEARCH =
  "FETCH_LIST_ATTRIBUTE_PRODUCT_SEARCH";

export const ADD_ATTRIBUTE_PRODUCT_SEARCH = "ADD_ATTRIBUTE_PRODUCT_SEARCH";
export const UPDATE_ATTRIBUTE_PRODUCT_SEARCH =
  "UPDATE_ATTRIBUTE_PRODUCT_SEARCH";
export const DELETE_ATTRIBUTE_PRODUCT_SEARCH =
  "DELETE_ATTRIBUTE_PRODUCT_SEARCH";

//Ecommerce
export const LIST_CONNECT_ECOMMERCE = "LIST_CONNECT_ECOMMERCE";
export const LIST_PRODUCTS_ECOMMERCE = "LIST_PRODUCTS_ECOMMERCE";
export const LIST_ORDERS_ECOMMERCE = "LIST_ORDERS_ECOMMERCE";
export const SYNC_PRODUCTS_FROM_STORES = "SYNC_PRODUCTS_FROM_STORES";
export const SYNC_ORDERS_FROM_STORES = "SYNC_ORDERS_FROM_STORES";

//Print Ecommerce
export const TYPE_PRINT_ECOMMERCE_A4_A5 = 1;
export const TYPE_PRINT_ECOMMERCE_TWO_VOLUME_A4 = 2;
export const TYPE_PRINT_ECOMMERCE_K80 = 3;
export const TYPE_PRINT_ECOMMERCE_LABEL = 4;

//Type Share Collaborator
export const TYPE_SHARE_COLLABORATOR_PERCENT = 0;
export const TYPE_SHARE_COLLABORATOR_NUMBER = 1;

//Status Bonus Point
export const STATUS_BONUS_POINT_PROCESSING = 0;
export const STATUS_BONUS_POINT_CANCEL = 1;
export const STATUS_BONUS_POINT_APPROVED = 2;
