export const ikitech_menu = [
  {
    title: "Menu",
    hasLinkShowWhenManyBranch: true,
    link: [
      {
        name: "Tổng quan",
        class: null,

        to: "/dashboard",
        icon: "fa fa-eye",
        isShowWhenManyBranch: true,
        exact: true,
      },

      // {
      //   name: "Bán hàng tại quầy",
      //   class: "create_order_pos",

      //   icon: "fa-credit-card",
      //   exact: true,
      //   to: "/pos",
      // },
      {
        name: "Đơn hàng",
        class: "order_list",
        isShowWhenManyBranch: true,
        icon: "fa-file-invoice",
        exact: true,
        to: "/order",
      },

      {
        name: "Sản phẩm",
        setOpenKey: ["/product/"],
        isShowWhenManyBranch: true,
        icon: "fas fa-th-large",
        open: "product",
        children: [
          {
            class: "product_list",
            display: "hide",
            name: "Sản phẩm",
            isShowWhenManyBranch: true,
            exact: true,
            to: "/product/index",
          },
          {
            class: "product_category_list",
            display: "hide",
            name: "Nhóm thuốc",
            isShowWhenManyBranch: true,
            exact: true,
            to: "/product/drug_group",
          },
          {
            class: "product_category_list",
            display: "hide",
            name: "Danh mục sản phẩm",
            isShowWhenManyBranch: true,
            exact: true,
            to: "/product/category",
          },
          {
            class: "product_category_list",
            display: "hide",
            name: "Thuộc tính tìm kiếm",
            isShowWhenManyBranch: true,
            exact: true,
            to: "/product/attribute_searches",
          },

          // {
          //     class: "customer_config_point",
          //     display: "hide",
          //     name: "In mã vạch",
          //     exact: true,
          //     to: "/product/index",
          // },
        ],
      },
      {
        name: "Gói sản phẩm",
        class: "create_order_pos",
        isShowWhenManyBranch: true,
        icon: "fas fa-th-large",
        exact: true,
        to: "/package_product",
      },
      {
        name: "Thưởng đạt điểm",
        class: "create_order_pos",
        icon: "fa fa-gift",
        exact: true,
        to: "/accumulate_point",
      },
      {
        name: "Sàn TMĐT",
        class: "ecommerce_list",
        setOpenKey: [
          "/ecommerce/manage",
          "/ecommerce/ecommerce_products/shopee",
          "/ecommerce/ecommerce_products/tiktok",
          "/ecommerce/ecommerce_products/lazada",
          "/ecommerce/ecommerce_products/tiki",
          "/ecommerce/ecommerce_orders/shopee",
          "/ecommerce/ecommerce_orders/tiktok",
          "/ecommerce/ecommerce_orders/lazada",
          "/ecommerce/ecommerce_orders/tiki",
        ],
        icon: "fas fa-th-large",
        open: "ecommerce",
        children: [
          {
            name: "Kết nối sàn TMĐT",
            class: "ecommerce_connect",
            display: "hide",
            exact: true,
            to: "/ecommerce/manage",
          },
          {
            class: "ecommerce_products",
            display: "hide",
            name: "Sản phẩm",
            exact: true,
            to: "",
            children: [
              {
                class: "ecommerce_products",
                display: "hide",
                name: "Shopee.vn",
                exact: true,
                to: "/ecommerce/ecommerce_products/shopee",
              },
              {
                class: "ecommerce_products",
                display: "hide",
                name: "Tiktok.com",
                exact: true,
                to: "/ecommerce/ecommerce_products/tiktok",
              },
              {
                class: "ecommerce_products",
                display: "hide",
                name: "Lazada.vn",
                exact: true,
                to: "/ecommerce/ecommerce_products/lazada",
              },
              {
                class: "ecommerce_products",
                display: "hide",
                name: "Tiki.vn",
                exact: true,
                to: "/ecommerce/ecommerce_products/tiki",
              },
            ],
          },
          {
            class: "ecommerce_orders",
            display: "hide",
            name: "Đơn hàng",
            exact: true,
            to: "",
            children: [
              {
                class: "ecommerce_orders",
                display: "hide",
                name: "Shopee.vn",
                exact: true,
                to: "/ecommerce/ecommerce_orders/shopee",
              },
              {
                class: "ecommerce_orders",
                display: "hide",
                name: "Tiktok.com",
                exact: true,
                to: "/ecommerce/ecommerce_orders/tiktok",
              },
              {
                class: "ecommerce_orders",
                display: "hide",
                name: "Lazada.vn",
                exact: true,
                to: "/ecommerce/ecommerce_orders/lazada",
              },
              {
                class: "ecommerce_orders",
                display: "hide",
                name: "Tiki.vn",
                exact: true,
                to: "/ecommerce/ecommerce_orders/tiki",
              },
            ],
          },
        ],
      },
      {
        name: "Kho",
        setOpenKey: [
          "/product_inventory/index",
          "/inventory/index",
          "/import_stocks/index",
          "/transfer_stocks/index",
          "/supplier",
        ],
        isShowWhenManyBranch: true,
        icon: "fas fa-store",
        open: "inventory",
        children: [
          {
            class: "inventory_list",
            display: "hide",
            name: "Tồn kho",
            exact: true,
            to: "/product_inventory/index",
            isShowWhenManyBranch: true,
          },
          {
            class: "inventory_tally_sheet",
            display: "hide",
            name: "Phiếu kiểm kho",
            exact: true,
            to: "/inventory/index",
          },
          {
            class: "inventory_import",
            display: "hide",
            name: "Nhập hàng",
            exact: true,
            to: "/import_stocks/index",
          },
          {
            class: "transfer_stock",
            display: "hide",
            name: "Chuyển kho",
            exact: true,
            to: "/transfer_stocks/index",
          },
          {
            name: "Nhà cung cấp",
            class: "supplier",
            display: "hide",
            exact: true,
            to: "/supplier",
          },
        ],
      },
      {
        name: "Báo cáo",
        setOpenKey: ["/report", "/report_"],
        isShowWhenManyBranch: true,
        icon: "fas fa-chart-bar",
        open: "report",
        children: [
          {
            // class: "report_finance",
            display: "hide",
            name: "Doanh thu thực",
            isShowWhenManyBranch: true,
            exact: true,
            to: "/report_revenue",
          },
          {
            display: "hide",
            name: "Doanh thu - lợi nhuận gộp",
            isShowWhenManyBranch: true,
            exact: true,
            to: "/report_gross_profit",
          },
          {
            display: "hide",
            name: "Doanh số sale",
            isShowWhenManyBranch: true,
            exact: true,
            to: "/report_sale",
          },
          {
            display: "hide",
            name: "Chi tiết nhập - bán hàng",
            isShowWhenManyBranch: true,
            exact: true,
            to: "/report_import_sale",
          },
          {
            display: "hide",
            name: "Báo cáo xuất nhập tồn",
            isShowWhenManyBranch: true,
            exact: true,
            to: "/report_import_export_inventory",
          },
          {
            display: "hide",
            name: "Theo dõi bán theo đơn",
            isShowWhenManyBranch: true,
            exact: true,
            to: "/report_watching_sell_by_order",
          },
        ],
      },
      {
        name: "Cài đặt",
        icon: "fas fa-cogs",
        setOpenKey: [
          "/theme",
          "/branch/index",
          "/staff/index",
          "/decentralization/index",
        ],

        open: "setting",
        children: [
          {
            name: "Chỉnh sửa website",
            class: "web_theme_edit",
            display: "hide",
            exact: true,
            to: "/theme",
          },

          {
            name: "Chi nhánh",
            class: "branch_list",
            display: "hide",
            exact: true,
            to: "/branch/index",
          },
          {
            name: "Nhân viên",
            class: "staff_list",
            display: "hide",
            exact: true,
            to: "/staff/index",
          },

          {
            name: "Chọn mẫu in",
            class: "config_setting",
            display: "hide",
            exact: true,
            to: "/invoice_template/index",
          },
          {
            name: "Cài đặt phân quyền",
            class: "decentralization_list",
            display: "hide",
            exact: true,
            to: "/decentralization/index",
          },

          {
            name: "Cài đặt quảng cáo",
            display: "hide",
            exact: true,
            to: "/banner_ads",
            class: "web_theme_edit",
          },

          {
            name: "Cài đặt chung",
            class: "config_setting",
            display: "hide",
            exact: true,
            to: "/setting/index",
          },
        ],
      },
      
    ],
  },
  {
    title: "Cài đặt riêng",
    hasLinkShowWhenManyBranch: false,
    link: [
      {
        class: "isVip",
        display: "hide",
        name: "Cài đặt cho VIP",
        icon: "fa-suitcase",
        exact: true,
        to: "/vip",
        isVip: true,
      },
    ],
  },
];
