export const dataOrderExample = {
    "id": 5791,
    "customer_id": 1837,
    "logged": true,
    "phone_number": "0942038103",
    "points_awarded_to_customer": 0,
    "order_code": "011122FJWY7NHM",
    "order_status": 4,
    "payment_status": 0,
    "payment_method_id": 0,
    "payment_partner_id": null,
    "partner_shipper_id": 0,
    "shipper_type": 0,
    "ship_discount_amount": 0,
    "total_shipping_fee": 55000,
    "balance_collaborator_used": 0,
    "bonus_points_amount_used": 0,
    "total_points_used": 0,
    "total_before_discount": 9000000,
    "combo_discount_amount": 0,
    "product_discount_amount": 0,
    "voucher_discount_amount": 0,
    "total_after_discount": 9000000,
    "discount": null,
    "total_final": 9055000,
    "total_money_refund": 0,
    "total_cost_of_capital": 0,
    "used_bonus_products": "[{\"quantity\":1,\"bonus_product\":{\"id\":204,\"name\":\"B\\u00e0o t\\u1eed l\\u1ee3i khu\\u1ea9n Intest Spo NSG\",\"start_time\":\"2022-11-01 00:00:00\",\"end_time\":\"2022-11-30 23:59:00\",\"multiply_by_number\":true}}]",
    "reviewed": false,
    "customer_name": "thu hà",
    "customer_country": 1,
    "customer_province": 96,
    "customer_province_name": "Tỉnh Cà Mau",
    "customer_district": 968,
    "customer_district_name": "Huyện Trần Văn Thời",
    "customer_wards": 32095,
    "customer_wards_name": "Thị trấn Trần Văn Thời",
    "customer_village": null,
    "customer_postcode": null,
    "customer_email": null,
    "customer_phone": "0942038103",
    "customer_address_detail": "khóm 5",
    "customer_note": null,
    "collaborator_by_customer_id": 1837,
    "agency_by_customer_id": null,
    "share_collaborator": 2700000,
    "point_for_agency": 0,
    "is_handled_balance_collaborator": false,
    "created_by_user_id": null,
    "created_by_staff_id": null,
    "from_pos": false,
    "order_from": 1,
    "branch_id": 788,
    "order_code_refund": null,
    "remaining_amount": 9055000,
    "has_refund_money_for_ctv": false,
    "has_refund_point_for_customer": true,
    "created_at": "2022-11-01 12:43:36",
    "updated_at": "2022-11-01 14:11:09",
    "sent_delivery": false,
    "payment_status_code": "UNPAID",
    "payment_status_name": "Chưa thanh toán",
    "order_status_code": "CUSTOMER_CANCELLED",
    "order_status_name": "Khách đã hủy",
    "payment_method_name": "Tiền mặt",
    "payment_partner_name": "Thanh toán khi nhận hàng",
    "shipper_name": "Giao hàng tiết kiệm",
    "customer_used_discount": [],
    "customer_used_combos": [],
    "customer_used_voucher": null,
    "customer_used_bonus_products": [
      {
        "quantity": 1,
        "bonus_product": {
          "id": 204,
          "name": "Bào tử lợi khuẩn Intest Spo NSG",
          "start_time": "2022-11-01 00:00:00",
          "end_time": "2022-11-30 23:59:00",
          "multiply_by_number": true
        }
      }
    ],
    "line_items_at_time": [
      {
        "id": 72703,
        "quantity": 5,
        "name": "BÀO TỬ LỢI KHUẨN INTEST SPO",
        "image_url": "https://data2.ikitech.vn/public/api/SahaImages/trTrQsqwSl1661396504.webp",
        "item_price": 300000,
        "main_price": 300000,
        "before_discount_price": 300000,
        "after_discount": 300000,
        "distributes_selected": null,
        "percent_collaborator": 30,
        "is_bonus": false
      },
      {
        "id": 72699,
        "quantity": 1,
        "name": "Cao ho bổ phổi HOÀNG BẢO ĐAN",
        "image_url": "https://data2.ikitech.vn/public/api/SahaImages/fEpWTFihqt1661396340.webp",
        "item_price": 220000,
        "main_price": 220000,
        "before_discount_price": 220000,
        "after_discount": 0,
        "distributes_selected": [
          {
            "name": null,
            "value": null,
            "sub_element_distributes": null
          }
        ],
        "percent_collaborator": 30,
        "is_bonus": true
      },
      {
        "id": 85163,
        "quantity": 5,
        "name": "Combo 05 Bào tử lợi khuẩn NSG TẶNG NGAY 02 Yến Sào NS One Nest",
        "image_url": "https://data2.ikitech.vn/public/api/SahaImages/zKivOVBMxK1667188324.webp",
        "item_price": 1500000,
        "main_price": 1500000,
        "before_discount_price": 1500000,
        "after_discount": 1500000,
        "distributes_selected": null,
        "percent_collaborator": 30,
        "is_bonus": false
      }
    ],
    "bonus_agency_history": null,
    "customer_address": {
      "name": "thu hà",
      "address_detail": "khóm 5",
      "country": 1,
      "province": 96,
      "district": 968,
      "wards": 32095,
      "village": null,
      "postcode": null,
      "email": null,
      "phone": "0942038103",
      "province_name": "Tỉnh Cà Mau",
      "district_name": "Huyện Trần Văn Thời",
      "wards_name": "Thị trấn Trần Văn Thời"
    },
    "branch": {
      "name": "Chi nhánh mặc định",
      "id": 788
    },
    "customer": {
      "id": 1837,
      "username": null,
      "area_code": "+84",
      "phone_number": "0942038103",
      "official": true,
      "phone_verified_at": null,
      "email": "dttha.th3khanhhung.pgdtvthoi@camau.edu.vn",
      "email_verified_at": null,
      "referral_phone_number": "0935002506",
      "name": "Đinh Thị Thu Hà",
      "name_str_filter": "dinh thi thu ha",
      "date_of_birth": "1979-10-02 00:00:00",
      "avatar_image": "https://data1.ikitech.vn/public/api/SahaImages/ssZeQZzSvX1660653754.jpg",
      "points": 8000,
      "sex": 2,
      "debt": 2300000,
      "is_collaborator": true,
      "is_passersby": false,
      "is_agency": false,
      "province": null,
      "district": null,
      "wards": null,
      "country_name": null,
      "province_name": null,
      "district_name": null,
      "wards_name": null,
      "address_detail": null,
      "is_from_json": false,
      "created_at": "2022-08-16 19:40:23",
      "updated_at": "2022-11-01 12:55:14",
      "total_referrals": 5
    },
    "line_items": [
      {
        "id": 30167,
        "customer_id": 1837,
        "phone_number": "0942038103",
        "device_id": null,
        "has_subtract_inventory": false,
        "element_distribute_id": null,
        "sub_element_distribute_id": null,
        "before_discount_price": 300000,
        "item_price": 300000,
        "cost_of_capital": 0,
        "quantity": 5,
        "total_refund": 0,
        "branch_id": 788,
        "is_refund": false,
        "is_bonus": false,
        "bonus_product_name": "",
        "distributes_selected": null,
        "reviewed": false,
        "product": {
          "id": 72703,
          "name": "BÀO TỬ LỢI KHUẨN INTEST SPO",
          "name_str_filter": "bao tu loi khuan intest spo",
          "sku": "565534923",
          "store_id": 770,
          "description": "Thương hiệu : INTEST SPO NSG Xuất xứ : Nguyên Sinh Group - Vi",
          "video_url": null,
          "view": 1553,
          "sold": 94,
          "likes": 0,
          "content_for_collaborator": "",
          "index_image_avatar": 0,
          "price": 300000,
          "min_price": 300000,
          "max_price": 300000,
          "import_price": 0,
          "default_price": 0,
          "quantity_in_stock": 478,
          "percent_collaborator": 30,
          "barcode": null,
          "status": 0,
          "check_inventory": true,
          "seo_title": "",
          "seo_description": "",
          "point_for_agency": 0,
          "created_at": "2022-08-01 21:48:17",
          "updated_at": "2022-11-11 13:34:07",
          "distributes": [],
          "product_discount": null,
          "quantity_in_stock_with_distribute": 478,
          "is_new": false,
          "is_top_sale": true,
          "is_favorite": false,
          "list_promotion": [],
          "slug": "bao-tu-loi-khuan-intest-spo",
          "inventory": null,
          "attributes": [],
          "images": [
            {
              "image_url": "https://data2.ikitech.vn/public/api/SahaImages/trTrQsqwSl1661396504.webp"
            },
            {
              "image_url": "https://data2.ikitech.vn/public/api/SahaImages/NqTSQbWeNN1659365230.webp"
            },
            {
              "image_url": "https://data2.ikitech.vn/public/api/SahaImages/uvWYEMrLmM1662363808.webp"
            },
            {
              "image_url": "https://data2.ikitech.vn/public/api/SahaImages/doPSJtNYMK1662363845.webp"
            },
            {
              "image_url": "https://data2.ikitech.vn/public/api/SahaImages/VVVNCAIItw1662363863.webp"
            }
          ]
        }
      },
      {
        "id": 30168,
        "customer_id": 1837,
        "phone_number": "0942038103",
        "device_id": null,
        "has_subtract_inventory": false,
        "element_distribute_id": null,
        "sub_element_distribute_id": null,
        "before_discount_price": 220000,
        "item_price": 0,
        "cost_of_capital": 0,
        "quantity": 1,
        "total_refund": 0,
        "branch_id": 788,
        "is_refund": false,
        "is_bonus": true,
        "bonus_product_name": "Bào tử lợi khuẩn Intest Spo NSG",
        "distributes_selected": [
          {
            "name": null,
            "value": null,
            "sub_element_distributes": null
          }
        ],
        "reviewed": false,
        "product": {
          "id": 72699,
          "name": "Cao ho bổ phổi HOÀNG BẢO ĐAN",
          "name_str_filter": "cao ho bo phoi hoang bao dan",
          "sku": "156076297",
          "store_id": 770,
          "description": "Thương hiệu : CAO BỔ PHỔI - HOÀNG BẢO ĐAN Xuất xứ: &nb",
          "video_url": null,
          "view": 823,
          "sold": 57,
          "likes": 0,
          "content_for_collaborator": "",
          "index_image_avatar": 0,
          "price": 220000,
          "min_price": 220000,
          "max_price": 220000,
          "import_price": 0,
          "default_price": 0,
          "quantity_in_stock": 473,
          "percent_collaborator": 30,
          "barcode": "",
          "status": 0,
          "check_inventory": true,
          "seo_title": "",
          "seo_description": "",
          "point_for_agency": 0,
          "created_at": "2022-08-01 21:15:26",
          "updated_at": "2022-11-11 12:18:48",
          "distributes": [],
          "product_discount": null,
          "quantity_in_stock_with_distribute": 473,
          "is_new": false,
          "is_top_sale": true,
          "is_favorite": false,
          "list_promotion": [],
          "slug": "cao-ho-bo-phoi-hoang-bao-dan",
          "inventory": null,
          "attributes": [],
          "images": [
            {
              "image_url": "https://data2.ikitech.vn/public/api/SahaImages/fEpWTFihqt1661396340.webp"
            },
            {
              "image_url": "https://data2.ikitech.vn/public/api/SahaImages/OfVBsjdPGR1659363251.webp"
            }
          ]
        }
      },
      {
        "id": 30169,
        "customer_id": 1837,
        "phone_number": "0942038103",
        "device_id": null,
        "has_subtract_inventory": false,
        "element_distribute_id": null,
        "sub_element_distribute_id": null,
        "before_discount_price": 1500000,
        "item_price": 1500000,
        "cost_of_capital": 0,
        "quantity": 5,
        "total_refund": 0,
        "branch_id": 788,
        "is_refund": false,
        "is_bonus": false,
        "bonus_product_name": "",
        "distributes_selected": null,
        "reviewed": false,
        "product": {
          "id": 85163,
          "name": "Combo 05 Bào tử lợi khuẩn NSG TẶNG NGAY 02 Yến Sào NS One Nest",
          "name_str_filter": "combo 05 bao tu loi khuan nsg tang ngay 02 yen sao ns one nest",
          "sku": "050207153",
          "store_id": 770,
          "description": "",
          "video_url": null,
          "view": 83,
          "sold": 7,
          "likes": 0,
          "content_for_collaborator": "",
          "index_image_avatar": 0,
          "price": 1500000,
          "min_price": 1500000,
          "max_price": 1500000,
          "import_price": 0,
          "default_price": 0,
          "quantity_in_stock": 49,
          "percent_collaborator": 30,
          "barcode": "",
          "status": 0,
          "check_inventory": true,
          "seo_title": "",
          "seo_description": "",
          "point_for_agency": null,
          "created_at": "2022-10-31 09:46:40",
          "updated_at": "2022-11-09 06:02:58",
          "distributes": [],
          "product_discount": null,
          "quantity_in_stock_with_distribute": 49,
          "is_new": true,
          "is_top_sale": true,
          "is_favorite": false,
          "list_promotion": [],
          "slug": "combo-05-bao-tu-loi-khuan-nsg-tang-ngay-02-yen-sao-ns-one-nest",
          "inventory": null,
          "attributes": [],
          "images": [
            {
              "image_url": "https://data2.ikitech.vn/public/api/SahaImages/zKivOVBMxK1667188324.webp"
            }
          ]
        }
      }
    ]
  }